# Generated by Django 4.2.7 on 2023-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSinceStart', models.FloatField(default=0)),
                ('errorMsg', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'CrashReport',
                'verbose_name_plural': 'CrashReports',
            },
        ),
    ]
