# Generated by Django 4.2.7 on 2023-11-07 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('crashTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('errorMsg', models.TextField(default='')),
                ('serviceName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CrashReport',
                'verbose_name_plural': 'CrashReports',
            },
        ),
    ]
