# Generated by Django 4.2.7 on 2023-11-06 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crashReports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashreport',
            name='timeSinceStart',
        ),
        migrations.AddField(
            model_name='crashreport',
            name='crashTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crashreport',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
